In [76]:
import numpy as np

In [77]:
np.__version__

'2.3.1'

list and array

In [78]:
lst=[1,2,3,4,5]
print(lst)
print(type(lst))
arr=np.array(lst)
print("array",arr)
print("type of arra",type(arr))

[1, 2, 3, 4, 5]
<class 'list'>
array [1 2 3 4 5]
type of arra <class 'numpy.ndarray'>


In [79]:
lst=list(range(0,21))

In [80]:
arr=np.array(lst)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [81]:
[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20]


[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]

In [82]:
arr=np.array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [83]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [84]:
np.arange(1,20)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [85]:
arr=np.zeros((5,10))
arr

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [86]:
arr.ndim

2

In [87]:
np.ones((5,10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [88]:
np.linspace(1,10,5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [89]:
arr=np.arange(0,30)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [90]:
arr.reshape(5,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [91]:
np.random.randint(1,5,9)

array([2, 1, 3, 3, 3, 1, 4, 4, 4], dtype=int32)

In [92]:
np.random.randint(1,5,(5,2))

array([[3, 3],
       [2, 4],
       [3, 1],
       [3, 1],
       [2, 4]], dtype=int32)

In [93]:
np.random.random(10)

array([0.14080149, 0.43813964, 0.96190704, 0.02373696, 0.03769569,
       0.51430798, 0.77707992, 0.0899787 , 0.26100939, 0.17008667])

In [94]:
arr=np.random.random((5,10))
arr.ndim

2

In [95]:
arr = np.arange(60).reshape(12,5)
print("shape of array",arr.shape)
print("size of array",arr.size)
print("dim of array",arr.ndim)
print("data type of arrray",arr.dtype)

shape of array (12, 5)
size of array 60
dim of array 2
data type of arrray int64


In [96]:
arr = np.arange(60).reshape(12,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59]])

In [97]:
arr.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [98]:
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [99]:
arr.shape

(12, 5)

In [100]:
arr.T.shape

(5, 12)

In [101]:
arr=np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [102]:
arr[0]=100

In [103]:
arr

array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9])

In [104]:
arr=np.arange(60).reshape(12,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59]])

In [105]:
arr[5]

array([25, 26, 27, 28, 29])

In [106]:
arr[5,4]

np.int64(29)

In [107]:
arr[0:5]

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [108]:
arr[0:5,1:2]

array([[ 1],
       [ 6],
       [11],
       [16],
       [21]])

In [109]:
arr[7:8,4]==100

array([False])

In [110]:
arr[11,4]

np.int64(59)

In [111]:
arr[12:5]

array([], shape=(0, 5), dtype=int64)

In [112]:
arr[11:,4:]

array([[59]])

In [113]:
arr[11][4]

np.int64(59)

In [114]:
arr[11][-1]

np.int64(59)

3D ARRAY

In [115]:
arr= np.array(np.arange(225).reshape(5,15,3))
arr

array([[[  0,   1,   2],
        [  3,   4,   5],
        [  6,   7,   8],
        [  9,  10,  11],
        [ 12,  13,  14],
        [ 15,  16,  17],
        [ 18,  19,  20],
        [ 21,  22,  23],
        [ 24,  25,  26],
        [ 27,  28,  29],
        [ 30,  31,  32],
        [ 33,  34,  35],
        [ 36,  37,  38],
        [ 39,  40,  41],
        [ 42,  43,  44]],

       [[ 45,  46,  47],
        [ 48,  49,  50],
        [ 51,  52,  53],
        [ 54,  55,  56],
        [ 57,  58,  59],
        [ 60,  61,  62],
        [ 63,  64,  65],
        [ 66,  67,  68],
        [ 69,  70,  71],
        [ 72,  73,  74],
        [ 75,  76,  77],
        [ 78,  79,  80],
        [ 81,  82,  83],
        [ 84,  85,  86],
        [ 87,  88,  89]],

       [[ 90,  91,  92],
        [ 93,  94,  95],
        [ 96,  97,  98],
        [ 99, 100, 101],
        [102, 103, 104],
        [105, 106, 107],
        [108, 109, 110],
        [111, 112, 113],
        [114, 115, 116],
        [117, 118, 11

In [116]:
arr[0][2:]

array([[ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [24, 25, 26],
       [27, 28, 29],
       [30, 31, 32],
       [33, 34, 35],
       [36, 37, 38],
       [39, 40, 41],
       [42, 43, 44]])

In [117]:
arr[:]

array([[[  0,   1,   2],
        [  3,   4,   5],
        [  6,   7,   8],
        [  9,  10,  11],
        [ 12,  13,  14],
        [ 15,  16,  17],
        [ 18,  19,  20],
        [ 21,  22,  23],
        [ 24,  25,  26],
        [ 27,  28,  29],
        [ 30,  31,  32],
        [ 33,  34,  35],
        [ 36,  37,  38],
        [ 39,  40,  41],
        [ 42,  43,  44]],

       [[ 45,  46,  47],
        [ 48,  49,  50],
        [ 51,  52,  53],
        [ 54,  55,  56],
        [ 57,  58,  59],
        [ 60,  61,  62],
        [ 63,  64,  65],
        [ 66,  67,  68],
        [ 69,  70,  71],
        [ 72,  73,  74],
        [ 75,  76,  77],
        [ 78,  79,  80],
        [ 81,  82,  83],
        [ 84,  85,  86],
        [ 87,  88,  89]],

       [[ 90,  91,  92],
        [ 93,  94,  95],
        [ 96,  97,  98],
        [ 99, 100, 101],
        [102, 103, 104],
        [105, 106, 107],
        [108, 109, 110],
        [111, 112, 113],
        [114, 115, 116],
        [117, 118, 11

In [118]:
arr[:,0,:]##

array([[  0,   1,   2],
       [ 45,  46,  47],
       [ 90,  91,  92],
       [135, 136, 137],
       [180, 181, 182]])

In [119]:
arr[:,0:1,0:1]

array([[[  0]],

       [[ 45]],

       [[ 90]],

       [[135]],

       [[180]]])

In [120]:
arr[2][3][1]=200

In [121]:
np.array([1,2,3,4,5,6,7])
arr.sort()

In [122]:
arr+2
arr*arr
arr/arr
arr-arr
arr+arr
arr/2


C:\Users\jangi\AppData\Local\Temp\ipykernel_3564\521199464.py:3: RuntimeWarning: invalid value encountered in divide
  arr/arr


array([[[  0. ,   0.5,   1. ],
        [  1.5,   2. ,   2.5],
        [  3. ,   3.5,   4. ],
        [  4.5,   5. ,   5.5],
        [  6. ,   6.5,   7. ],
        [  7.5,   8. ,   8.5],
        [  9. ,   9.5,  10. ],
        [ 10.5,  11. ,  11.5],
        [ 12. ,  12.5,  13. ],
        [ 13.5,  14. ,  14.5],
        [ 15. ,  15.5,  16. ],
        [ 16.5,  17. ,  17.5],
        [ 18. ,  18.5,  19. ],
        [ 19.5,  20. ,  20.5],
        [ 21. ,  21.5,  22. ]],

       [[ 22.5,  23. ,  23.5],
        [ 24. ,  24.5,  25. ],
        [ 25.5,  26. ,  26.5],
        [ 27. ,  27.5,  28. ],
        [ 28.5,  29. ,  29.5],
        [ 30. ,  30.5,  31. ],
        [ 31.5,  32. ,  32.5],
        [ 33. ,  33.5,  34. ],
        [ 34.5,  35. ,  35.5],
        [ 36. ,  36.5,  37. ],
        [ 37.5,  38. ,  38.5],
        [ 39. ,  39.5,  40. ],
        [ 40.5,  41. ,  41.5],
        [ 42. ,  42.5,  43. ],
        [ 43.5,  44. ,  44.5]],

       [[ 45. ,  45.5,  46. ],
        [ 46.5,  47. ,  47.5],
    